version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Web UI -> http://localhost:15672  (user/pass: guest/guest)

  # one-shot container that publishes 10 tasks and exits
  producer:
    build: ./producer
    depends_on:
      - rabbitmq
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672

  # stateless worker image – we scale it at runtime
  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
